# Generated by Django 5.1.6 on 2025-03-22 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('commenting_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replying_to', to='core.comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comment', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(unique=True, upload_to='files')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comment', verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('assignees', models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='assignees')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issue', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('pinned_for', models.ManyToManyField(related_name='pinned_for', to=settings.AUTH_USER_MODEL, verbose_name='pin')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issues', verbose_name='issue'),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=50)),
                ('object', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status', 'Status'), ('priority', 'Priority'), ('type', 'Type'), ('pinned', 'Pinned'), ('locked', 'Locked'), ('name', 'Name'), ('description', 'Description')], max_length=20)),
                ('previous_name', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_desc', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issues', verbose_name='issue')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='plan'),
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_priority', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='plan')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priority'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_status', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='plan')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.CreateModel(
            name='ChartObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='creator')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_type', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='plan')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.types'),
        ),
    ]
