# Generated by Django 5.1.6 on 2025-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_issues_name_alter_plan_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='status',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='types',
            name='plan',
        ),
        migrations.AddField(
            model_name='priority',
            name='plan',
            field=models.ManyToManyField(to='core.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='status',
            name='plan',
            field=models.ManyToManyField(to='core.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='types',
            name='plan',
            field=models.ManyToManyField(to='core.plan', verbose_name='plan'),
        ),
    ]
