# Generated by Django 5.1.6 on 2025-04-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_priority_plan_remove_status_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.priority'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.types'),
        ),
    ]
