# Generated by Django 5.1.6 on 2025-07-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_assigned', models.BooleanField(default=True)),
                ('issue_unassigned', models.BooleanField(default=True)),
                ('issue_status', models.BooleanField(default=True)),
                ('issue_priority', models.BooleanField(default=True)),
                ('issue_type', models.BooleanField(default=True)),
                ('issue_pinned', models.BooleanField(default=True)),
                ('issue_unpinned', models.BooleanField(default=True)),
                ('issue_locked', models.BooleanField(default=True)),
                ('issue_unlocked', models.BooleanField(default=True)),
                ('issue_name', models.BooleanField(default=True)),
                ('issue_desc', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
